version: "3.7"

services:
  sample:
    container_name: ssl-docker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "8080:80"
      - "443:443"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
